// Libellé français + couleur pour chaque `action_type` de activity_log. Partagé entre
// le journal complet (Historique.jsx) et le widget « Activité récente » du tableau de
// bord Superadmin, pour ne pas afficher le type brut ("conge_demande") aux deux endroits.
export const ACTION_LABELS = {
  invitation_envoyee: { label: 'Invitation envoyée', color: 'bg-blue-50 text-blue-600' },
  lien_inscription_envoye: { label: "Lien d'inscription envoyé", color: 'bg-blue-50 text-blue-600' },
  compte_confirme: { label: 'Compte confirmé', color: 'bg-green-50 text-status-approved' },
  compte_refuse: { label: 'Compte refusé', color: 'bg-red-50 text-status-rejected' },
  compte_desactive: { label: 'Compte désactivé', color: 'bg-red-50 text-status-rejected' },
  compte_reactive: { label: 'Compte réactivé', color: 'bg-green-50 text-status-approved' },
  compte_supprime: { label: 'Compte supprimé', color: 'bg-red-50 text-status-rejected' },
  element_restaure: { label: 'Élément restauré', color: 'bg-green-50 text-status-approved' },
  element_supprime_definitivement: { label: 'Suppression définitive', color: 'bg-red-50 text-status-rejected' },
  corbeille_videe: { label: 'Corbeille vidée', color: 'bg-red-50 text-status-rejected' },
  notification_envoyee: { label: 'Notification', color: 'bg-purple-50 text-purple-600' },
  conge_demande: { label: 'Demande de congé', color: 'bg-amber-50 text-status-pending' },
  conge_traite: { label: 'Congé traité', color: 'bg-green-50 text-status-approved' },
  conge_avis_intermediaire: { label: 'Avis intermédiaire congé', color: 'bg-amber-50 text-status-pending' },
  conge_justificatif_ajoute: { label: 'Justificatif de congé ajouté', color: 'bg-amber-50 text-status-pending' },
  fonction_modifiee: { label: 'Changement de grade', color: 'bg-indigo-50 text-indigo-600' },
  carriere_evenement: { label: 'Événement de carrière', color: 'bg-indigo-50 text-indigo-600' },
  carriere_evenement_modifie: { label: 'Événement de carrière modifié', color: 'bg-indigo-50 text-indigo-600' },
  carriere_evenement_supprime: { label: 'Événement de carrière supprimé', color: 'bg-indigo-50 text-indigo-600' },
  diplome_ajoute: { label: 'Diplôme ajouté', color: 'bg-indigo-50 text-indigo-600' },
  diplome_supprime: { label: 'Diplôme supprimé', color: 'bg-indigo-50 text-indigo-600' },
  situation_administrative: { label: 'Situation administrative', color: 'bg-indigo-50 text-indigo-600' },
  situation_administrative_modifiee: { label: 'Situation administrative modifiée', color: 'bg-indigo-50 text-indigo-600' },
  situation_administrative_supprimee: { label: 'Situation administrative supprimée', color: 'bg-red-50 text-status-rejected' },
  contrat_importe: { label: 'Contrat importé', color: 'bg-teal-50 text-teal-600' },
  contrat_document_ajoute: { label: 'Document de contrat ajouté', color: 'bg-teal-50 text-teal-600' },
  contrat_decision: { label: 'Décision sur un contrat', color: 'bg-teal-50 text-teal-600' },
  contrat_renouvele: { label: 'Contrat renouvelé', color: 'bg-teal-50 text-teal-600' },
  document_demande: { label: 'Document demandé', color: 'bg-purple-50 text-purple-600' },
  document_demande_traitee: { label: 'Demande de document traitée', color: 'bg-purple-50 text-purple-600' },
  document_demande_refusee: { label: 'Demande de document refusée', color: 'bg-red-50 text-status-rejected' },
  document_genere: { label: 'Document généré', color: 'bg-purple-50 text-purple-600' },
  personnel_cree: { label: 'Fiche personnel créée', color: 'bg-blue-50 text-blue-600' },
  personnel_importe: { label: 'Personnel importé', color: 'bg-blue-50 text-blue-600' },
  personnel_infos_modifiees: { label: 'Informations personnelles modifiées', color: 'bg-blue-50 text-blue-600' },
  personnel_modifie_par_rh: { label: 'Fiche modifiée par la RH', color: 'bg-blue-50 text-blue-600' },
  mot_de_passe_modifie: { label: 'Mot de passe modifié', color: 'bg-gray-100 text-gray-600' },
  mot_de_passe_reinitialise: { label: 'Mot de passe réinitialisé', color: 'bg-gray-100 text-gray-600' },
  apparence_modifiee: { label: 'Apparence modifiée', color: 'bg-gray-100 text-gray-600' },
  texte_modifie: { label: 'Texte modifié', color: 'bg-gray-100 text-gray-600' },
  parametre_carriere_modifie: { label: 'Paramètre de carrière modifié', color: 'bg-gray-100 text-gray-600' },
  permission_modifiee: { label: 'Permission modifiée', color: 'bg-gray-100 text-gray-600' },
  conge_ouverture_saisie: { label: 'Solde de congé saisi', color: 'bg-amber-50 text-status-pending' },
  organisation_direction_creee: { label: 'Direction créée', color: 'bg-blue-50 text-blue-600' },
  organisation_direction_supprimee: { label: 'Direction supprimée', color: 'bg-red-50 text-status-rejected' },
  organisation_service_cree: { label: 'Service créé', color: 'bg-blue-50 text-blue-600' },
  organisation_service_supprime: { label: 'Service supprimé', color: 'bg-red-50 text-status-rejected' },
  connexion: { label: 'Connexion', color: 'bg-gray-100 text-gray-600' },
  reclamation_deposee: { label: 'Réclamation déposée', color: 'bg-amber-50 text-status-pending' },
  reclamation_traitee: { label: 'Réclamation traitée', color: 'bg-green-50 text-status-approved' },
};

// Types considérés comme de « l'activité du personnel » (congés, documents,
// carrière/dossier) — utilisé pour mettre en avant ces événements plutôt que les
// connexions ou les actions d'administration système sur le tableau de bord Superadmin.
export const PERSONNEL_ACTION_TYPES = new Set([
  'conge_demande', 'conge_traite', 'conge_avis_intermediaire', 'conge_justificatif_ajoute',
  'fonction_modifiee', 'carriere_evenement', 'carriere_evenement_modifie', 'carriere_evenement_supprime',
  'diplome_ajoute', 'diplome_supprime',
  'situation_administrative', 'situation_administrative_modifiee', 'situation_administrative_supprimee',
  'contrat_importe', 'contrat_document_ajoute', 'contrat_decision', 'contrat_renouvele',
  'document_demande', 'document_demande_traitee', 'document_demande_refusee', 'document_genere',
  'personnel_cree', 'personnel_importe', 'personnel_infos_modifiees', 'personnel_modifie_par_rh',
  'reclamation_deposee',
]);
